### ISSUE TITLE
timestamp conversion fail after switching to new API

### ISSUE THREAD

**Issue by janstarke** [dfir-dd/dfir-toolkit#44]
```
test output::csv_output::tests::test_correct_ts_random_tz ... FAILED
test output::txt_output::tests::test_correct_ts_random_tz ... FAILED
test output::csv_output::tests::test_correct_ts_UTC ... FAILED
test output::txt_output::tests::test_correct_ts_UTC ... FAILED

failures:

---- output::csv_output::tests::test_correct_ts_random_tz stdout ----
thread 'output::csv_output::tests::test_correct_ts_random_tz' panicked at src/bin/mactime2/output/csv_output.rs:99:13:
assertion `left == right` failed: Timestamp 2037489506 converted to '2024-05-16T03:45:46-04:00' and back to 1715831146 (offset was -14400s)
  left: 2037489506
 right: 1715831146
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- output::txt_output::tests::test_correct_ts_random_tz stdout ----
thread 'output::txt_output::tests::test_correct_ts_random_tz' panicked at src/bin/mactime2/output/txt_output.rs:118:13:
assertion `left == right` failed: Timestamp 1352388422 converted to '2024-05-16T03:45:46-04:00' and back to 1715831146 (offset was -14400s)
  left: 1352388422
 right: 1715831146

---- output::csv_output::tests::test_correct_ts_UTC stdout ----
thread 'output::csv_output::tests::test_correct_ts_UTC' panicked at src/bin/mactime2/output/csv_output.rs:67:13:
assertion `left == right` failed: Timestamp 3898258695 converted to '2024-05-16T07:45:46+00:00' and back to 1715845546
  left: 3898258695
 right: 1715845546

---- output::txt_output::tests::test_correct_ts_UTC stdout ----
thread 'output::txt_output::tests::test_correct_ts_UTC' panicked at src/bin/mactime2/output/txt_output.rs:83:13:
assertion `left == right` failed: Timestamp 630314567 converted to '2024-05-16T07:45:46+00:00' and back to 1715845546
  left: 630314567
 right: 1715845546


failures:
    output::csv_output::tests::test_correct_ts_UTC
    output::csv_output::tests::test_correct_ts_random_tz
    output::txt_output::tests::test_correct_ts_UTC
    output::txt_output::tests::test_correct_ts_random_tz

test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `--bin mactime2`

```

**Comment by janstarke** [comment]
fixed by #45
